---
apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: busy-box
  name: client-shenlel
spec:
  containers:
  - image: registry.moqi.com.cn/baseimage/alpine
    name: client
    command: ["/bin/sh", "-c"]
    args: ["/usr/bin/tail", "-f", "/etc/hosts"]
    tty: true
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
