apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  accessModes:       
    - ReadWriteOnce
  capacity:          
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 172.20.35.104
    path: /u01/prod/postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: sonarqube
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: postgres
