apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  accessModes:       
    - ReadWriteOnce
  capacity:          
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard  
  nfs:
    server: 172.20.35.104
    path: /u01/prod/sonarqube
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: sonarqube
