---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-test-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openresty
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - name: openresty
        image: openresty/openresty:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
        - name: web-data
          mountPath: "/usr/share/nginx/html"
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: glusterfs-test-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

