---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: psql
spec:
  selector:
    matchLabels:
      app: psql 
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: mfs/postgres:10
          imagePullPolicy: IfNotPresent
          ports:
            - name: psql
              containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None
  selector:
    app: psql

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: psql
spec:
  entryPoints:
    - psql
  routes:
  - match: HostSNI(`psql.idocker.io`)
    services:
    - name: postgresql
      port: 5432
