---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: devops
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: harbor.ccav.tech/flask/hello-world-uwsgi-nginx:python3.6-alpine3.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: devops
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 8010
  selector:
    app: flask
