---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-1
  namespace: devops
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /u01/prod/mysql/mysql-datadir-1
    server: 172.20.35.104
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-2
  namespace: devops
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /u01/prod/mysql/mysql-datadir-2
    server: 172.20.35.104
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-3
  namespace: devops
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /u01/prod/mysql/mysql-datadir-3
    server: 172.20.35.104
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-4
  namespace: devops
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /u01/prod/mysql/mysql-datadir-4
    server: 172.20.35.104
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-5
  namespace: devops
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /u01/prod/mysql/mysql-datadir-5
    server: 172.20.35.104
