---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: moqi
        - name: MYSQL_DATABASE
          value: moqi_ops
        - name: MYSQL_USER
          value: moqi
        - name: MYSQL_PASSWORD
          value: moqi233
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: ceph-rbd-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql
spec:
  entryPoints:
    - psql
  routes:
  - match: HostSNI(`mysql.ops.internal.moqi.ai`)
    services:
    - name: mysql
      port: 3306
