---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-datadir-pv
  namespace: devops
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.20.35.104
    path: /u02/prod/jenkins/jenkins-data 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-root-datadir-pv
  namespace: devops
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.20.35.104
    path: /u02/prod/jenkins/jenkins-root-data
