kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: provider
  name: provider-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider-spec
        image: harbor.ccav.tech/dubbo/dubbo-demo-provider:v2.1.5
        #command: ["/apps/tomcat/bin/run_tomcat.sh"]
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 20880
          protocol: TCP
          name: http

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: provider
  name: provider-spec
  namespace: devops
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 20880
    #nodePort: 30001
  selector:
    app: devopsprovider
