kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: consumer
  name: consumer-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer-spec
        image: harbor.ccav.tech/dubbo/dubbo-demo-consumer:v2.1.5
        #command: ["/apps/tomcat/bin/run_tomcat.sh"]
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          name: http

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: consumer
  name: consumer-spec
  namespace: devops
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 30001
  selector:
    app: consumer
